/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrarItemRouteImport } from './routes/cadastrar-item'
import { Route as SolicitarRetiradaIdRouteImport } from './routes/solicitar-retirada.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarItemRoute = CadastrarItemRouteImport.update({
  id: '/cadastrar-item',
  path: '/cadastrar-item',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarRetiradaIdRoute = SolicitarRetiradaIdRouteImport.update({
  id: '/solicitar-retirada/$id',
  path: '/solicitar-retirada/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar-item': typeof CadastrarItemRoute
  '/solicitar-retirada/$id': typeof SolicitarRetiradaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar-item': typeof CadastrarItemRoute
  '/solicitar-retirada/$id': typeof SolicitarRetiradaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar-item': typeof CadastrarItemRoute
  '/solicitar-retirada/$id': typeof SolicitarRetiradaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastrar-item' | '/solicitar-retirada/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastrar-item' | '/solicitar-retirada/$id'
  id: '__root__' | '/' | '/cadastrar-item' | '/solicitar-retirada/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarItemRoute: typeof CadastrarItemRoute
  SolicitarRetiradaIdRoute: typeof SolicitarRetiradaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-item': {
      id: '/cadastrar-item'
      path: '/cadastrar-item'
      fullPath: '/cadastrar-item'
      preLoaderRoute: typeof CadastrarItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar-retirada/$id': {
      id: '/solicitar-retirada/$id'
      path: '/solicitar-retirada/$id'
      fullPath: '/solicitar-retirada/$id'
      preLoaderRoute: typeof SolicitarRetiradaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarItemRoute: CadastrarItemRoute,
  SolicitarRetiradaIdRoute: SolicitarRetiradaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
